# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

WORKDIR /app

# Copy server code
COPY server.py ./

# Install dependencies
RUN pip install --no-cache-dir mcp requests pycountry

# Default command
CMD ["python", "server.py"]
